/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Modelo.*;

/**
 *
 * @author Usuario
 */
public class VentanaRetirarVehiculo extends javax.swing.JFrame {

    private Parqueadero parqueadero = VentanaPrincipal.parqueadero;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRetirarVehiculo.class.getName());

    /**
     * Creates new form VentanaRetirarVehiculo
     */
    public VentanaRetirarVehiculo(Parqueadero parqueadero) {
        initComponents();
        this.parqueadero = parqueadero;
    }

    private VentanaRetirarVehiculo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPlacaR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPermanencia = new javax.swing.JTextField();
        btnFactura = new javax.swing.JButton();
        rbMinutos = new javax.swing.JRadioButton();
        rbHoras = new javax.swing.JRadioButton();
        btnVolver = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retirar Vehiculo");

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel2.setText("DATOS");

        jLabel1.setText("Ingrese la placa del vehiculo:");

        txtPlacaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaRActionPerformed(evt);
            }
        });

        jLabel3.setText("Tiempo de permanencia del vehiculo:");

        btnFactura.setText("Generar Factura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMinutos);
        rbMinutos.setText("Minutos");
        rbMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMinutosActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbHoras);
        rbHoras.setText("Horas");
        rbHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHorasActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver al menú");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtPlacaR, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlacaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMinutos)
                    .addComponent(rbHoras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
        try {

            String placa = txtPlacaR.getText().trim();
            if (placa.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Debe ingresar la placa.",
                        "Error",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            Vehiculo vehiculo = null;
            for (Vehiculo v : parqueadero.getVehiculosDentro()) {
                if (v.getPlaca().equalsIgnoreCase(placa)) {
                    vehiculo = v;
                    break;
                }
            }

            if (vehiculo == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No existe un vehículo con esa placa dentro del parqueadero.",
                        "Error",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            String permanenciaStr = txtPermanencia.getText().trim();
            if (!permanenciaStr.matches("\\d+")) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "La permanencia debe ser un número entero.",
                        "Error",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            int tiempo = Integer.parseInt(permanenciaStr);
            int horasSimuladas = tiempo;

            if (rbMinutos.isSelected()) {
                horasSimuladas = (int) Math.ceil(tiempo / 60.0);
            } else if (!rbHoras.isSelected()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Debe seleccionar minutos u horas.",
                        "Error",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            Factura factura = new Factura(vehiculo, horasSimuladas);

            double tarifa = parqueadero.retirarVehiculo(vehiculo.getPlaca());

            if (tarifa >= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Vehículo retirado");
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se encontró el vehículo con esa placa.");
            }

            VentanaFactura ventanaFactura = new VentanaFactura(factura);
            ventanaFactura.setVisible(true);

            txtPlacaR.setText("");
            txtPermanencia.setText("");
            rbHoras.setSelected(false);
            rbMinutos.setSelected(false);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnFacturaActionPerformed

    private void rbMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMinutosActionPerformed

    }//GEN-LAST:event_rbMinutosActionPerformed

    private void rbHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHorasActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtPlacaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaRetirarVehiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton rbHoras;
    private javax.swing.JRadioButton rbMinutos;
    private javax.swing.JTextField txtPermanencia;
    private javax.swing.JTextField txtPlacaR;
    // End of variables declaration//GEN-END:variables
}
